import type {
  ActivityLog,
  DischargeSummary,
  HandoverNote,
  Patient,
  ProblemMaster,
  ProblemProgressEntry,
  TaskTemplate,
  TaskUpdate,
  UserProfile,
  Ward,
  WardTask,
} from "@/lib/types";

export const demoUser: UserProfile = {
  id: "demo-user-1",
  name: "Dr. Nicha S.",
  email: "demo@wardflow.local",
  avatarUrl: null,
  role: "admin",
  wardAssignment: "ward-med-a",
};

export const demoWards: Ward[] = [
  { id: "ward-med-a", name: "Medical A" },
  { id: "ward-icu", name: "ICU Step-down" },
];

export const demoProfiles: UserProfile[] = [
  demoUser,
  {
    id: "demo-user-2",
    name: "Dr. Pakorn R.",
    email: "pakorn@wardflow.local",
    avatarUrl: null,
    role: "resident",
    wardAssignment: "ward-med-a",
  },
  {
    id: "demo-user-3",
    name: "Student Mint K.",
    email: "mint@wardflow.local",
    avatarUrl: null,
    role: "student",
    wardAssignment: "ward-med-a",
  },
];

export const demoPatientsSeed: Patient[] = [
  {
    id: "patient-1",
    wardId: "ward-med-a",
    bed: "12",
    hospitalNumber: "HN6600012",
    admissionNumber: "AN26070001",
    displayName: "S. Woranit",
    age: 71,
    sex: "F",
    underlyingDisease: "CKD stage 3, hypertension, diabetes mellitus",
    diagnosis: "Pneumonia with AKI",
    status: "critical",
    responsibleDoctorId: "demo-user-1",
    responsibleDoctorName: "Dr. Nicha S.",
    allergy: "Penicillin",
    precaution: "droplet",
    codeStatus: "Full code",
    lifecycle: "active",
    dischargedAt: null,
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "patient-2",
    wardId: "ward-med-a",
    bed: "15",
    hospitalNumber: "HN6600015",
    admissionNumber: "AN26070009",
    displayName: "K. Thanawat",
    age: 56,
    sex: "M",
    underlyingDisease: "Alcohol-related cirrhosis",
    diagnosis: "Decompensated cirrhosis",
    status: "watch",
    responsibleDoctorId: "demo-user-2",
    responsibleDoctorName: "Dr. Pakorn R.",
    allergy: null,
    precaution: "none",
    codeStatus: "Limited escalation",
    lifecycle: "active",
    dischargedAt: null,
    lastUpdate: new Date(Date.now() - 1000 * 60 * 27).toISOString(),
  },
  {
    id: "patient-3",
    wardId: "ward-icu",
    bed: "2A",
    hospitalNumber: "HN6600021",
    admissionNumber: "AN26070014",
    displayName: "P. Arisara",
    age: 44,
    sex: "F",
    underlyingDisease: "Systemic lupus erythematosus",
    diagnosis: "Septic shock recovery",
    status: "stable",
    responsibleDoctorId: "demo-user-1",
    responsibleDoctorName: "Dr. Nicha S.",
    allergy: null,
    precaution: "contact",
    codeStatus: "Full code",
    lifecycle: "active",
    dischargedAt: null,
    lastUpdate: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    id: "patient-4",
    wardId: "ward-med-a",
    bed: "20",
    hospitalNumber: "HN6600028",
    admissionNumber: "AN26069971",
    displayName: "P. Chanin",
    age: 64,
    sex: "M",
    underlyingDisease: "Type 2 diabetes mellitus",
    diagnosis: "Cellulitis improved",
    status: "stable",
    responsibleDoctorId: "demo-user-2",
    responsibleDoctorName: "Dr. Pakorn R.",
    allergy: null,
    precaution: "none",
    codeStatus: "Full code",
    lifecycle: "discharged",
    dischargedAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    lastUpdate: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
];

export const demoProblemMastersSeed: ProblemMaster[] = [
  {
    id: "problem-1",
    patientId: "patient-1",
    problemName: "Hypoxemia overnight",
    priority: "ACTIVE_UNSTABLE",
    currentStatusSummary: "Still needs 5 L/min oxygen overnight after PLEX.",
    diagnosisStatus: "CONFIRMED",
    includeInHandover: true,
    sortOrder: 1,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
    updatedAt: new Date().toISOString(),
    resolvedAt: null,
  },
  {
    id: "problem-2",
    patientId: "patient-1",
    problemName: "AKI on CKD",
    priority: "ACTIVE_STABLE",
    currentStatusSummary: "Renal function remains above baseline with borderline urine output.",
    diagnosisStatus: "CONFIRMED",
    includeInHandover: true,
    sortOrder: 2,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 9).toISOString(),
    updatedAt: new Date().toISOString(),
    resolvedAt: null,
  },
  {
    id: "problem-3",
    patientId: "patient-2",
    problemName: "Ascites control",
    priority: "MONITORING",
    currentStatusSummary: "Symptoms improved after tap; monitoring for re-accumulation.",
    diagnosisStatus: "CONFIRMED",
    includeInHandover: true,
    sortOrder: 1,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    updatedAt: new Date().toISOString(),
    resolvedAt: null,
  },
];

export const demoProblemProgressEntriesSeed: ProblemProgressEntry[] = [
  {
    id: "problem-progress-1",
    problemId: "problem-1",
    dateTime: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
    authorId: "demo-user-2",
    authorName: "Dr. Pakorn R.",
    statusUpdate: "Stable after PLEX but still needs 5 L/min oxygen overnight.",
    newEvidence: "O2 requirement up to 5L/min, CXR infiltrate worse at right lower zone, ABG pending.",
    treatmentChange: "Broad-spectrum antibiotics, oxygen titration, chest physiotherapy.",
    reasoningUpdate:
      "Clinical deterioration and rising oxygen need support active pulmonary process; no immediate fluid overload signs.",
    todayPlan: "Repeat CXR, trend SpO2 closely, review ABG and escalate if oxygen rises again.",
    pendingTaskIds: ["task-1", "task-2"],
    createdAt: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
  },
  {
    id: "problem-progress-2",
    problemId: "problem-2",
    dateTime: new Date(Date.now() - 1000 * 60 * 70).toISOString(),
    authorId: "demo-user-1",
    authorName: "Dr. Nicha S.",
    statusUpdate: "Renal function remains above baseline but urine output still present.",
    newEvidence: "Cr 2.4 from baseline 1.6, urine output borderline, no severe hyperkalemia.",
    treatmentChange: "Review fluid balance, avoid nephrotoxins, strict input/output charting.",
    reasoningUpdate:
      "AKI is likely multifactorial from sepsis and volume shifts; improvement will depend on perfusion and infection control.",
    todayPlan: "Repeat renal panel, review fluid responsiveness, adjust antibiotics to renal dose.",
    pendingTaskIds: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 70).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 70).toISOString(),
  },
  {
    id: "problem-progress-3",
    problemId: "problem-3",
    dateTime: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    authorId: "demo-user-2",
    authorName: "Dr. Pakorn R.",
    statusUpdate: "Symptoms improved after tap, now under monitoring for re-accumulation.",
    newEvidence: "Abdominal discomfort reduced after tap, blood pressure stable, culture pending.",
    treatmentChange: "Continue albumin support, daily weight, and salt restriction.",
    reasoningUpdate:
      "Response after drainage supports tense ascites as the main symptom driver; still need culture to exclude SBP.",
    todayPlan: "Follow ascitic culture, review weight and renal function.",
    pendingTaskIds: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
];

export const demoTasksSeed: WardTask[] = [
  {
    id: "task-1",
    patientId: "patient-1",
    problemId: "problem-1",
    title: "Follow culture result",
    note: "Escalate if resistant organism",
    ownerId: "demo-user-2",
    ownerName: "Dr. Pakorn R.",
    status: "in_progress",
    priority: "emergency",
    type: "lab",
    dueAt: new Date(Date.now() + 1000 * 60 * 90).toISOString(),
    blockedReason: null,
    updatedById: "demo-user-1",
    updatedByName: "Dr. Nicha S.",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "task-2",
    patientId: "patient-1",
    problemId: "problem-1",
    title: "Talk to family",
    note: "Discuss possible ICU step-up",
    ownerId: "demo-user-1",
    ownerName: "Dr. Nicha S.",
    status: "in_progress",
    priority: "urgent",
    type: "family_talk",
    dueAt: new Date(Date.now() + 1000 * 60 * 40).toISOString(),
    blockedReason: null,
    updatedById: "demo-user-1",
    updatedByName: "Dr. Nicha S.",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "task-3",
    patientId: "patient-2",
    problemId: null,
    title: "Arrange discharge meds",
    note: "Need med reconciliation first",
    ownerId: "demo-user-3",
    ownerName: "Student Mint K.",
    status: "blocked",
    priority: "normal",
    type: "medication",
    dueAt: null,
    blockedReason: "Pharmacy list pending",
    updatedById: "demo-user-3",
    updatedByName: "Student Mint K.",
    updatedAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  },
];

export const demoTaskUpdatesSeed: TaskUpdate[] = [
  {
    id: "task-update-1",
    taskId: "task-1",
    note: "Sent culture request, waiting lab release.",
    createdById: "demo-user-2",
    createdByName: "Dr. Pakorn R.",
    createdAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
  },
  {
    id: "task-update-2",
    taskId: "task-1",
    note: "Prelim report seen, no resistant organism yet.",
    createdById: "demo-user-1",
    createdByName: "Dr. Nicha S.",
    createdAt: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
  },
  {
    id: "task-update-3",
    taskId: "task-3",
    note: "Waiting pharmacy med reconciliation list.",
    createdById: "demo-user-3",
    createdByName: "Student Mint K.",
    createdAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
  },
];

export const demoHandoverSeed: HandoverNote[] = [
  {
    id: "handover-1",
    patientId: "patient-1",
    note: "High risk for respiratory deterioration overnight.",
    escalationInstruction: "Call IM resident if sat < 92% despite 5L O2",
    updatedAt: new Date().toISOString(),
  },
];

export const demoDischargeSummarySeed: DischargeSummary[] = [
  {
    id: "discharge-summary-1",
    patientId: "patient-4",
    wardId: "ward-med-a",
    createdById: "demo-user-2",
    createdByName: "Dr. Pakorn R.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    admitDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    dischargeDate: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    lengthOfStay: "3 days",
    primaryDiagnosis: "Cellulitis improved",
    hospitalCourse: "Improved with IV antibiotics and step-down monitoring.",
    plan: "Complete outpatient follow-up and continue wound care.",
    homeMedication: "",
  },
];

export const demoActivitySeed: ActivityLog[] = [
  {
    id: "activity-1",
    patientId: "patient-1",
    actorId: "demo-user-1",
    actorName: "Dr. Nicha S.",
    action: "patient.created",
    entityType: "patient",
    entityId: "patient-1",
    beforeJson: null,
    afterJson: { diagnosis: "Pneumonia with AKI", status: "critical" },
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: "activity-2",
    patientId: "patient-1",
    actorId: "demo-user-2",
    actorName: "Dr. Pakorn R.",
    action: "task.updated",
    entityType: "ward_task",
    entityId: "task-1",
    beforeJson: { status: "not_started" },
    afterJson: { status: "in_progress" },
    createdAt: new Date(Date.now() - 1000 * 60 * 28).toISOString(),
  },
  {
    id: "activity-3",
    patientId: "patient-4",
    actorId: "demo-user-2",
    actorName: "Dr. Pakorn R.",
    action: "patient.created",
    entityType: "patient",
    entityId: "patient-4",
    beforeJson: null,
    afterJson: { diagnosis: "Cellulitis improved", status: "stable" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  },
];

export const demoTemplatesSeed: TaskTemplate[] = [
  { id: "template-1", title: "Follow lab", type: "lab", defaultPriority: "normal" },
  { id: "template-2", title: "Follow culture", type: "lab", defaultPriority: "urgent" },
  {
    id: "template-3",
    title: "Consult",
    type: "consult",
    defaultPriority: "urgent",
  },
  {
    id: "template-4",
    title: "Talk to family",
    type: "family_talk",
    defaultPriority: "normal",
  },
  {
    id: "template-5",
    title: "Discharge summary",
    type: "discharge",
    defaultPriority: "normal",
  },
  { id: "template-6", title: "Home meds", type: "medication", defaultPriority: "normal" },
  { id: "template-7", title: "Appointment", type: "other", defaultPriority: "normal" },
  {
    id: "template-8",
    title: "Procedure prep",
    type: "procedure",
    defaultPriority: "urgent",
  },
];
