import type {
  ActivityLog,
  HandoverNote,
  Patient,
  Problem,
  TaskTemplate,
  UserProfile,
  Ward,
  WardTask,
} from "@/lib/types";

export const demoUser: UserProfile = {
  id: "demo-user-1",
  name: "Dr. Nicha S.",
  email: "demo@wardflow.local",
  avatarUrl: null,
  role: "admin",
  wardAssignment: "ward-med-a",
};

export const demoWards: Ward[] = [
  { id: "ward-med-a", name: "Medical A" },
  { id: "ward-icu", name: "ICU Step-down" },
];

export const demoProfiles: UserProfile[] = [
  demoUser,
  {
    id: "demo-user-2",
    name: "Dr. Pakorn R.",
    email: "pakorn@wardflow.local",
    avatarUrl: null,
    role: "resident",
    wardAssignment: "ward-med-a",
  },
  {
    id: "demo-user-3",
    name: "Student Mint K.",
    email: "mint@wardflow.local",
    avatarUrl: null,
    role: "student",
    wardAssignment: "ward-med-a",
  },
];

export const demoPatientsSeed: Patient[] = [
  {
    id: "patient-1",
    wardId: "ward-med-a",
    bed: "12",
    displayName: "S. Woranit",
    age: 71,
    sex: "F",
    diagnosis: "Pneumonia with AKI",
    status: "critical",
    responsibleDoctorId: "demo-user-1",
    responsibleDoctorName: "Dr. Nicha S.",
    allergy: "Penicillin",
    isolationFlag: true,
    codeStatus: "Full code",
    lifecycle: "active",
    dischargedAt: null,
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "patient-2",
    wardId: "ward-med-a",
    bed: "15",
    displayName: "K. Thanawat",
    age: 56,
    sex: "M",
    diagnosis: "Decompensated cirrhosis",
    status: "watch",
    responsibleDoctorId: "demo-user-2",
    responsibleDoctorName: "Dr. Pakorn R.",
    allergy: null,
    isolationFlag: false,
    codeStatus: "Limited escalation",
    lifecycle: "active",
    dischargedAt: null,
    lastUpdate: new Date(Date.now() - 1000 * 60 * 27).toISOString(),
  },
  {
    id: "patient-3",
    wardId: "ward-icu",
    bed: "2A",
    displayName: "P. Arisara",
    age: 44,
    sex: "F",
    diagnosis: "Septic shock recovery",
    status: "stable",
    responsibleDoctorId: "demo-user-1",
    responsibleDoctorName: "Dr. Nicha S.",
    allergy: null,
    isolationFlag: false,
    codeStatus: "Full code",
    lifecycle: "active",
    dischargedAt: null,
    lastUpdate: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    id: "patient-4",
    wardId: "ward-med-a",
    bed: "20",
    displayName: "P. Chanin",
    age: 64,
    sex: "M",
    diagnosis: "Cellulitis improved",
    status: "stable",
    responsibleDoctorId: "demo-user-2",
    responsibleDoctorName: "Dr. Pakorn R.",
    allergy: null,
    isolationFlag: false,
    codeStatus: "Full code",
    lifecycle: "discharged",
    dischargedAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    lastUpdate: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
];

export const demoProblemsSeed: Problem[] = [
  {
    id: "problem-1",
    patientId: "patient-1",
    title: "Hypoxemia overnight",
    status: "worsening",
    keyData: "O2 requirement up to 5L/min",
    plan: "Repeat CXR and monitor saturation trend",
    pending: "Await ABG",
    watchOut: "Desaturation during transfer",
    includeInHandover: true,
    sortOrder: 1,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "problem-2",
    patientId: "patient-1",
    title: "AKI on CKD",
    status: "active",
    keyData: "Cr 2.4 from baseline 1.6",
    plan: "Review fluids, strict I/O",
    pending: "Repeat renal panel",
    watchOut: "Low urine output",
    includeInHandover: true,
    sortOrder: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "problem-3",
    patientId: "patient-2",
    title: "Ascites control",
    status: "improving",
    keyData: "Abdominal discomfort reduced after tap",
    plan: "Continue albumin and daily weight",
    pending: "Await ascitic culture",
    watchOut: "Hypotension",
    includeInHandover: true,
    sortOrder: 1,
    updatedAt: new Date().toISOString(),
  },
];

export const demoTasksSeed: WardTask[] = [
  {
    id: "task-1",
    patientId: "patient-1",
    title: "Follow culture result",
    note: "Escalate if resistant organism",
    ownerId: "demo-user-2",
    ownerName: "Dr. Pakorn R.",
    status: "in_progress",
    priority: "emergency",
    type: "lab",
    dueAt: new Date(Date.now() + 1000 * 60 * 90).toISOString(),
    blockedReason: null,
    updatedById: "demo-user-1",
    updatedByName: "Dr. Nicha S.",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "task-2",
    patientId: "patient-1",
    title: "Talk to family",
    note: "Discuss possible ICU step-up",
    ownerId: "demo-user-1",
    ownerName: "Dr. Nicha S.",
    status: "in_progress",
    priority: "urgency",
    type: "family_talk",
    dueAt: new Date(Date.now() + 1000 * 60 * 40).toISOString(),
    blockedReason: null,
    updatedById: "demo-user-1",
    updatedByName: "Dr. Nicha S.",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "task-3",
    patientId: "patient-2",
    title: "Arrange discharge meds",
    note: "Need med reconciliation first",
    ownerId: "demo-user-3",
    ownerName: "Student Mint K.",
    status: "blocked",
    priority: "normal",
    type: "medication",
    dueAt: null,
    blockedReason: "Pharmacy list pending",
    updatedById: "demo-user-3",
    updatedByName: "Student Mint K.",
    updatedAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  },
];

export const demoHandoverSeed: HandoverNote[] = [
  {
    id: "handover-1",
    patientId: "patient-1",
    note: "High risk for respiratory deterioration overnight.",
    escalationInstruction: "Call IM resident if sat < 92% despite 5L O2",
    updatedAt: new Date().toISOString(),
  },
];

export const demoActivitySeed: ActivityLog[] = [
  {
    id: "activity-1",
    patientId: "patient-1",
    actorId: "demo-user-1",
    actorName: "Dr. Nicha S.",
    action: "patient.created",
    entityType: "patient",
    entityId: "patient-1",
    beforeJson: null,
    afterJson: { diagnosis: "Pneumonia with AKI", status: "critical" },
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: "activity-2",
    patientId: "patient-1",
    actorId: "demo-user-2",
    actorName: "Dr. Pakorn R.",
    action: "task.updated",
    entityType: "ward_task",
    entityId: "task-1",
    beforeJson: { status: "not_started" },
    afterJson: { status: "in_progress" },
    createdAt: new Date(Date.now() - 1000 * 60 * 28).toISOString(),
  },
];

export const demoTemplatesSeed: TaskTemplate[] = [
  { id: "template-1", title: "Follow lab", type: "lab", defaultPriority: "normal" },
  { id: "template-2", title: "Follow culture", type: "lab", defaultPriority: "urgency" },
  {
    id: "template-3",
    title: "Consult specialist",
    type: "consult",
    defaultPriority: "urgency",
  },
  {
    id: "template-4",
    title: "Talk to family",
    type: "family_talk",
    defaultPriority: "normal",
  },
  {
    id: "template-5",
    title: "Discharge summary",
    type: "discharge",
    defaultPriority: "normal",
  },
  { id: "template-6", title: "Home meds", type: "medication", defaultPriority: "normal" },
  { id: "template-7", title: "Appointment", type: "other", defaultPriority: "normal" },
  {
    id: "template-8",
    title: "Procedure prep",
    type: "procedure",
    defaultPriority: "urgency",
  },
];
